model_database/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^$', views.home),
    url(r'^models/', include('visualize.urls')), 
    url(r'^admin/', admin.site.urls),
] + static( settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT )

urlpatterns += staticfiles_urlpatterns()

visualize/urls.py
from django.conf.urls import url
from . import views

# dispatch URLS here
app_name = 'visualize'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^upload/', views.upload, name='upload'),
    url(r'^(?P<simulation_id>[0-9]+)/$', views.detail, name='detail'),
]

visualize/models.py
from __future__ import unicode_literals
from django.db import models
# these fields are only used for referencing, so they will all be forced to
# 

# General simulation
class Simulation( models.Model ):
    # TODO: These values will come with post request, user and upload_date, think about validating data client side and sending json over
    user = models.CharField(max_length=200, blank=True)
    name = models.CharField(max_length=200, default='', null=True, blank=True, unique=True)
    upload_date = models.DateTimeField(auto_now_add=True)
    comments = models.TextField(null=True, blank=True)
    
    def get_fields(self):
        ignore = ['id']
        fields = [(field.name, field.value_to_string(self)) for field in Simulation._meta.fields if field.name not in ignore and field.value_to_string(self)]
        return fields

    def get_field_names(self):
        ignore = ['id']
        fields = [field.name for field in Simulation._meta.fields if field.name not in ignore]

    def __unicode__(self):
        return self.name
    
# Stores simulation output data
class Simulation_Input( models.Model ):
    simulation = models.ForeignKey(Simulation, on_delete=models.CASCADE)
    file = models.CharField(max_length=200, null=True, blank=True)
    field = models.CharField(max_length=200)
    val = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        unique_together = ["simulation", "field"]

    def get_fields(self):
        ignore = ['simulation', 'id']
        fields = [(field.name, field.value_to_string(self)) for field in Simulation_Input._meta.fields if field.name not in ignore and field.value_to_string(self)]
        return fields

    def __unicode__(self):
        return self.simulation.name + ': ' + self.field

class Simulation_Output( models.Model ):
    simulation = models.ForeignKey(Simulation, on_delete=models.CASCADE)
    file = models.CharField(max_length=200)
    field = models.CharField(max_length=200)
    shape = models.CharField(max_length=200)
    indices = models.CharField(max_length=200)

    class Meta:
        unique_together = ["simulation", "file"]

    def get_fields(self):
        ignore = ['simulation', 'id']
        fields = [(field.name, field.value_to_string(self)) for field in Simulation_Output._meta.fields if field.name not in ignore and field.value_to_string(self)]
        return fields

    def __unicode__(self):
        return self.simulation.name + ': ' + self.field


# Handles tagging for Simulations to create user-defined queries.
class Tag(models.Model):
    name = models.TextField()
    simulation = models.ManyToManyField( Simulation )

class Parameters( models.Model ):
    bc1 = models.TextField() 
    bc2 = models.TextField()
    delts = models.TextField()
    dt = models.TextField()
    dx = models.TextField() 
    eplasticity = models.TextField()
    faultnormal = models.TextField()
    friction = models.TextField()
    ihypo = models.TextField()
    np3 = models.TextField()
    npml = models.TextField()
    nt = models.TextField()
    nn = models.TextField()
    rundir = models.TextField()
    pcdep = models.TextField(null=True, blank=True)
    rcrit = models.TextField(null=True, blank=True)
    delts = models.TextField(null=True, blank=True)
    tm0 = models.TextField(null=True, blank=True)
    tmnucl = models.TextField(null=True, blank=True)
    trelax = models.TextField(null=True, blank=True)
    simulation = models.OneToOneField( Simulation, on_delete=models.CASCADE, primary_key = True )

    def get_fields(self):
        ignore = ['simulation']
        fields = [(field.name, field.value_to_string(self)) for field in Parameters._meta.fields if field.name not in ignore and field.value_to_string(self)]
        return fields

    def __unicode__(self):
        return self.simulation.name + " parameters"

class Rupture_Parameters( models.Model ):
    simulation = models.OneToOneField( Simulation, on_delete=models.CASCADE, primary_key=True)
    fault_extent = models.FloatField()
    magnitude = models.FloatField()
    del_tau = models.FloatField()

    def get_fields(self):
        ignore = ['simulation']
        fields = [(field.name, field.value_to_string(self)) for field in Rupture_Parameters._meta.fields if field.name not in ignore and field.value_to_string(self)]
        return fields

class OnePoint(models.Model):
    simulation = models.OneToOneField( Simulation, on_delete=models.CASCADE, primary_key=True)
    avg_slip_tr = models.FloatField()
    avg_psv_tr = models.FloatField() 
    avg_vrup_tr = models.FloatField()
    std_slip_tr = models.FloatField()
    std_psv_tr = models.FloatField() 
    std_vrup_tr = models.FloatField()
    avg_slip_sa = models.FloatField()
    avg_psv_sa = models.FloatField() 
    avg_vrup_sa = models.FloatField()
    std_slip_sa = models.FloatField()
    std_psv_sa = models.FloatField() 
    std_vrup_sa = models.FloatField()
    med_slip_sa = models.FloatField()
    med_psv_sa = models.FloatField() 
    med_vrup_sa = models.FloatField()
    mad_slip_sa = models.FloatField()
    mad_psv_sa = models.FloatField() 
    mad_vrup_sa = models.FloatField()
    med_del_tau = models.FloatField()
    avg_del_tau = models.FloatField()

    def get_fields(self):
        ignore = ['simulation']
        fields = [(field.name, field.value_to_string(self)) for field in OnePoint._meta.fields if field.name not in ignore and field.value_to_string(self)]
        return fields

class Figure(models.Model):
    simulation = models.ForeignKey( Simulation, on_delete=models.CASCADE )
    name = models.TextField()
    # make an admin site for this
    title = models.TextField(null=True, blank=True)
    file_path = models.TextField()
    upload_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    notes = models.TextField(null=True, blank=True)
    active = models.BooleanField(default=True)

    class Meta:
        get_latest_by = "modified_date"

    def __unicode__(self):
        return self.simulation.name + ":" + self.name + ' -- ' + str(self.upload_date)

visualize/forms.py
# python imports
import json

# django imports
from django import forms
from django.forms import ModelForm

# user defines imports
from .models import Simulation, Simulation_Input, Simulation_Output, Parameters, Rupture_Parameters, OnePoint
from .models import Figure
class SimulationForm(ModelForm):
    class Meta:
        model = Simulation
        exclude = ['comments','upload_date']

class SimulationOutputForm(ModelForm):
    class Meta:
        model = Simulation_Output 
        exclude = ['simulation']

class SimulationInputForm(ModelForm):
    class Meta:
        model = Simulation_Input
        exclude = ['simulation']

class ParametersForm(ModelForm):
    class Meta:
        model = Parameters
        exclude = ['simulation']

    def __unicode__(self):
        return 'parameters model'

class RuptureParametersForm(ModelForm):
    class Meta:
        model = Rupture_Parameters
        exclude = ['simulation']

    def __unicode__(self):
        return 'rupture parameters model'

class OnePointForm(ModelForm):
    class Meta:
        model = OnePoint
        exclude = ['simulation']

    def __unicode__(self):
        return 'one point statistics'

class FigureForm(ModelForm):
    class Meta:
        model = Figure
        exclude = ['simulation']

    def __unicode__(self):
        return "figure product"

class ActivateFigureForm(ModelForm):
    class Meta:
        model = Figure
        fields = ('active',)

    def __unicode__(self):
        return 'activate/deactive figure form'




class UploadFileForm( forms.Form ):
    file = forms.FileField()

    # handle file parsing here.
    def clean_file(self):
        data = self.cleaned_data['file']
        files = self.parse_file(data)

        # form = SimulationModelForm(data=data_dict)
        # if form.is_valid():
        #     self.instance = form.save(commit=False)
        # else:
        #     raise forms.ValidationError(u'The file contains invalid data.')
        return data


    def save(self):
        instance = getattr(self, "instance", None)
        if instance:
            instance.save()
        return instance

    # custom for SORD parameters.json file
    def parse_file(self, data):
        # data_dict={}
        # columns = [val.name for val in Simulation._meta.get_fields()]
        # json_data = json.loads(''.join(data.readlines()))
        # for key, val in json_data.iteritems():
        #     if key in columns:
        #         data_dict[key]=val
        try:
            files = [item.strip() or None for item in data]
            self.cleaned_data['files'] = files
        except Exception as e:
            print "unable to read upload file. make sure there is one directory per line."
        return files

visualize/views.py
#python includes
import os, logging

# django includes
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.exceptions import ObjectDoesNotExist

# my includes
from .models import Simulation, Parameters, Rupture_Parameters,OnePoint,Figure
from .models import Simulation_Input, Simulation_Output
from .tasks import process_and_upload_simulations_task

""" upload method will accept a list of folders that need to be operated on. these should be transfered to the server already. 
    after they are done uploading they will redirect to models. new models will be visible from models page. """
def upload(request):
    if request.method == 'POST':
        if request.is_ajax():
            post = request.POST.get('post');
            clean_post = _cleanse_post( post )
            if clean_post:
                for file in clean_post:
                    process_and_upload_simulations_task.delay( file )
                response = { 'status' : 'success' }
            else:
                response = { 'status' : 'failed' }
            return JsonResponse(response)
    return render(request, 'visualize/upload.html')

def detail(request, simulation_id):
    # probably a better way to grab shit from the database
    # maybe wrap into single massive query
    simulation_list = Simulation.objects.order_by('upload_date')
    simulation = get_object_or_404(Simulation, pk=simulation_id)
    parameters = _get_or_none(Parameters, simulation=simulation)
    rupture = _get_or_none(Rupture_Parameters, simulation=simulation)
    one_point = _get_or_none(OnePoint, simulation=simulation)
    inp = _get_many_or_none(Simulation_Input, simulation=simulation)
    outp = _get_many_or_none(Simulation_Output, simulation=simulation)
    figs = _get_figures(simulation)
    context = {
               'list': simulation_list, 
               'par': parameters, 
               'sim': simulation,
               'rup': rupture, 
               'one_point': one_point, 
               'figs': figs, 
               'inp': inp, 
               'outp': outp
              }
    return render(request, 'visualize/detail.html', context)

def index(request):
    simulation_list = Simulation.objects.order_by('upload_date')
    context = {'simulation_list': simulation_list }
    return render( request, 'visualize/index.html', context )


def _cleanse_post( post ):
    """ checks whether the input files sent are valid. aka exist in specified location on server. """
    exists = True

    # shortcut, obvious first.
    if not post:
        return False

    # list of files to return
    out = []

    # maybe it has several files
    try:
        files = post.split('\n')
        for f in files:
            if f and not os.path.isdir( f ):
                exists = False
            elif f and os.path.isdir( f ):
                out.append( f )

    # be more specific
    except Exception as e:
        logging.info('unable to iterate on post, trying as single file.\nerror msg: %s' % str(e))
        # maybe it has one file
        try:
            if not os.path.isdir( post ):
                exists = False
            else:
                out.append( f )
        except Exception as e:
            logging.error('unable to use as single file. failing.\nerror msg: %s' % str(e))
            exists = False

    # phew, made it thru
    logging.info('exists: %s' % str(exists))
    return out

def _get_or_none( model_class, **kwargs ):
    try:
        query = model_class.objects.get( **kwargs )
    # could check if object does not exist, but we want none if it doesn't work
    except:
        query = None
    return query

def _get_many_or_none( model_class, **kwargs ):
    try:
        query = model_class.objects.filter( **kwargs )
    except:
        query = None
    return query

def _get_figures( fk ):
    try:
        query = Figure.objects.filter(simulation=fk, active=True).values('file_path','name')
    except:
        query = None
    return query

visualize/templates/visualize/base.html
<html>
<head>
	<title>Model Database</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	{% block header %}
	{% endblock %}
</head>

<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">pyorogeny</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/models">Models</a></li>
      <li><a href="/models/upload">Upload</a></li>
    </ul>
  </div>
</nav>

<div class="container">
	<div class="row">
		<div class="col-md-4">
			{% block left-sidebar %}
			{% endblock %}
		</div>
		<div class="col-md-8">
			{% block content %} 
			{% endblock %} 
		</div>
	</div>
</div>

</body>
</html>

visualize/templates/visualize/base_fluid.html
<html>
<head>
	<title>Model Database</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	{% block header %}
	{% endblock %}
</head>

<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">pyorogeny</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/models">Models</a></li>
      <li><a href="/models/upload">Upload</a></li>
    </ul>
  </div>
</nav>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			{% block content %} 
			{% endblock %} 
		</div>
	</div>
</div>

</body>
</html>

visualize/templates/visualize/debug.html
<p> {{ type }} </p>

visualize/templates/visualize/detail.html
{% extends "visualize/base.html" %}
{% load staticfiles %}

{% block header %}
	<link rel="stylesheet" type="text/css" href="{% static 'visualize/detail.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'visualize/w3.css' %}" />
{% endblock %}
{% block left-sidebar %}
<h2>Simulation List</h2>
{% if list %}
    {% for simulation in list %}
    <a href="{% url 'visualize:detail' simulation.id %}">{{ simulation.name }}</a><br>
    {% endfor %}
{% else %}
    <p>No simulations available.</p>
{% endif %}
{% endblock %}
{% block content %}
<ul class="nav nav-tabs">
	<li class="active"><a data-toggle="tab" href="#tab-overview">Overview</a></li>
	<li><a data-toggle="tab" href="#tab-figures">Figures</a></li>
	<li><a data-toggle="tab" href="#tab-parameters">Parameters</a></li>
	<li><a data-toggle="tab" href="#tab-outputs">Output</a></li>
</ul>
<div class="tab-content">
	<div id = "tab-overview" class="tab-pane fade in active">
		<h2>Simulation {{sim.name}} </h2>
		<p>{{ sim.comments }}</p>
		{% if rup %}
		<h2>Rupture Details</h2>
		<table>
		<tr>
			<th>Parameter</th>
			<th>Value</th>
		</tr>
		{% for name, value in rup.get_fields %}
		<tr>
			<td>{{ name }}</td>
			<td>{{ value }}</td>
		</tr>
		{% endfor %}
		</table>
		{% endif %}

		{% if one_point %}
		<h2>One Point Statistics</h2>
		<table>
		<tr>
			<th>Parameter</th>
			<th>Value</th>
		</tr>
		{% for name, value in one_point.get_fields %}
		<tr>
			<td>{{ name }}</td>
			<td>{{ value }}</td>
		</tr>
		{% endfor %}
		</table>
		{% endif %}
	</div>

	<div id = "tab-figures" class="tab-pane fade">
		<h2>Figures</h2>
		{% if figs %}
			<div id="carousel" class="carousel slide" data-ride="carousel" data-interval="false">
			<div class="carousel-inner" role="listbox">
			{% for fig in figs %}
				{% if forloop.first %}
				<div class="item active">
				{% else %}
				<div class="item">
				{% endif %}
				<h3>{{ fig.name }}</h3>
				<img src="{{MEDIA_URL}}visualize/models/{{fig.file_path}}" style="width:100%">
				</div>
			{% endfor %}
			</div>
			<a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
			    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			    <span class="sr-only">Previous</span>
		  	</a>
		    <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
			    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			    <span class="sr-only">Next</span>
			</a>
			</div>
		{% else %}
		<p>There are no figures to display for this model.</p>
		{% endif %}
	</div>

	<div id="tab-parameters" class="tab-pane fade">
		{% if par %}
		<h2>Simulation Parameters</h2>
		<table>
		<tr>
			<th>Parameters</th>
			<th>Value</th>
		</tr>
		{% for name, value in par.get_fields %}
		<tr>
		    <td>{{ name }}</td>
		    <td>{{ value }}</td>
		</tr>
		{% endfor %}
		</table>
		{% endif %}
		{% if inp %}
		<h2>Simulation Inputs</h2>
		<table>
		<tr>
			<th>Field</th>
			<th>Val</th>
		</tr>
		{% for i in inp %}
		<tr>
			<td>{{ i.field }}</td>
			{% if i.val %}
				<td>{{ i.val }}</td>
			{% elif i.file %}
				<td>{{i.file }}</td>
			{% endif %}
		</tr>
		{% endfor %}
		</table>
		{% endif %}
	</div>

	<div id="tab-outputs" class="tab-pane fade">
		{% if outp %}
		<h2>Simulation Outputs</h2>
		<table>
		<tr>
			<th>File</th>
			<th>Field</th>
			<th>Shape</th>
			<th>Indices</th>
		</tr>
		{% for out in outp %}
		<tr>
			<td>{{ out.file }}</td>
			<td>{{ out.field }}</td>
			<td>{{ out.shape }}</td>
			<td>{{ out.indices }}</td>
		</tr>
		{% endfor %}
		</table>
		{% endif %}
		</div>
	</div>
<script type="text/javascript" src="{% static 'visualize/detail.js' %}"/></script>
{% endblock %}

visualize/templates/visualize/index.html
{% extends "visualize/base_fluid.html" %}
{% block content %}
<h2>Simulation List</h2>
{% if simulation_list %}
    <ul>
    {% for simulation in simulation_list %}
    <li><a href="{% url 'visualize:detail' simulation.id %}">{{ simulation.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No simulations available.</p>
{% endif %}
{% endblock %}

visualize/templates/visualize/upload.html
{% extends "visualize/base_fluid.html" %}
{% block header %}
{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'visualize/upload.css' %}" />
{% endblock %}
{% block content %}
<div class="well">
	<p>
		<h3>Upload SORD Simulation</h3>
		Upload text file containing full file-path of simulation directory on the server.  Make sure correct data files reside in a directory labed 'out' and magnitude file is located in a directory called 'stats'.
	</p>
</div>
<div id='form'>
	<form method="post">
		{% csrf_token %}
		<div class="fileUpload btn btn-primary">
			<span>Choose Files</span>
		    <input class='upload' id="file" type="file" name="file"><br>
		</div>
		<div class="fileUpload btn btn-primary">
			<span>Upload</span>
		    <input class='upload' type="button" id='submit' value="Upload File"><br>
		</div>
	</form>
</div>
<div id='message'>
</div>
<script type="text/javascript" src="{% static 'visualize/upload.js' %}"/></script>
{% endblock %}